# Generated by Django 5.0.2 on 2024-02-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_catalog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(choices=[('все', 'все'), ('сварка', 'сварка'), ('котлы', 'котлы'), ('плазменная резка', 'плазменная резка'), ('ворота', 'ворота'), ('калитки', 'калитки'), ('другое', 'другое')], max_length=50),
        ),
    ]
